I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_timur_ch3.rpy", line 256, in script
    play music EvaMemories fadein 1.0
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/script_timur_ch3.rpy", line 256, in <module>
    play music EvaMemories fadein 1.0
NameError: name 'EvaMemories' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_timur_ch3.rpy", line 256, in script
    play music EvaMemories fadein 1.0
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\ast.py", line 2259, in execute
    self.call("execute")
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script_timur_ch3.rpy", line 256, in <module>
    play music EvaMemories fadein 1.0
NameError: name 'EvaMemories' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.2.23090503
Ты не один 0.1
Mon Feb 24 17:33:43 2025
